### ISSUE TITLE
Implement control panel GUI

### ISSUE THREAD

**Issue by stormbringer951** [stormbringer951/CaptainsLog#33]
- [x] ~~Remove FleetLogIntel editor~~ Rename, change to small intel and add some functionality
- [x] Visual GUI to trigger InteractionDialog for creating new log
- [x] Change name to be more representative of new purpose and avoid having to fully qualify `com.fs.starfarer.api.impl.campaign.intel.misc.FleetLogIntel` when both imported
- [x] Set shortcut to be the same as for creating logs when in campaign script

**Comment by jaghaimo** [comment]
What (class) name should it be given?

**Comment by stormbringer951** [comment]
> What (class) name should it be given?

Not 100% pinned down on a name, something like `LogSettingsIntel` or `SettingsBoardIntel` would be good, I think.

IIRC, my understanding of the current aim for this class is to convert it to do filtering/visual settings/other management stuff.

I'd also ideally like it to control hiding/showing/ignoring automatically created intel classes too, but that may be feature creep and require a different settings intel under a different tag.
