### ISSUE TITLE
Bug + Suggestions

### ISSUE THREAD

**Issue by JamesTripleQ** [stormbringer951/CaptainsLog#43]
**Bug:**

There is an issue where immediately after salvaging something, if you quickly go to the "Salvage" tab and click "Lay in Course" you will be able to salvage the same thing again.

**Suggestions:**

-Make the AddStablePoint command a cheat command,
-Turn the "Cryosleepers" tab to a "Megastructures" tab which includes cryosleepers, hypershunts and, if you have industrial evolution enabled, the automated ship yards.

I made a custom build of your mod intended  purely for personal use that adds and fixes these things... if you want I can make a pull request just keep a few things in mind:
-the code is intentionally not clean and designed to edit the least amount of things as possible,
-my solution for the bug was removing the "Lay in Course" button from a bunch of things,
-I did not ask SirHartley for permission for compatibility yet as this was for personal use.

**Comment by stormbringer951** [comment]
Hey there @JamesTripleQ,

> I made a custom build of your mod intended purely for personal use that adds and fixes these things... if you want I can make a pull request just keep a few things in mind

I might not directly merge the pull request but will be looking at that. Minimal changes are fine; I have several other things I need to merge that make much more sweeping changes to the intel items anyway.

Wrt permissions I have other features planned for next version that optionally integrate with IndEvo (or did anyway; not sure if those features have changed by now in IndEvo) that requires contacting Hartley so I can handle that
